apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry
  namespace: registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: kind
    app.kubernetes.io/name: registry
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: kind
      app.kubernetes.io/name: registry
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kind
        app.kubernetes.io/name: registry
    spec:
      serviceAccountName: registry
      containers:
      - image: registry:2
        name: registry
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
        ports:
          - name: http-registry
            protocol: TCP
            containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: kind
  namespace: registry
spec:
  type: NodePort
  ports:
    - name: http-registry
      port: 5000
      protocol: TCP
      targetPort: 5000
      nodePort: 32000
  selector:
    app.kubernetes.io/instance: kind
    app.kubernetes.io/name: registry
