/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	scheme "github.com/youniqx/heist/pkg/client/heist.youniqx.com/v1alpha1/clientset/heist/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VaultKVSecretEnginesGetter has a method to return a VaultKVSecretEngineInterface.
// A group's client should implement this interface.
type VaultKVSecretEnginesGetter interface {
	VaultKVSecretEngines(namespace string) VaultKVSecretEngineInterface
}

// VaultKVSecretEngineInterface has methods to work with VaultKVSecretEngine resources.
type VaultKVSecretEngineInterface interface {
	Create(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.CreateOptions) (*v1alpha1.VaultKVSecretEngine, error)
	Update(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (*v1alpha1.VaultKVSecretEngine, error)
	UpdateStatus(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (*v1alpha1.VaultKVSecretEngine, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VaultKVSecretEngine, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VaultKVSecretEngineList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultKVSecretEngine, err error)
	VaultKVSecretEngineExpansion
}

// vaultKVSecretEngines implements VaultKVSecretEngineInterface
type vaultKVSecretEngines struct {
	client rest.Interface
	ns     string
}

// newVaultKVSecretEngines returns a VaultKVSecretEngines
func newVaultKVSecretEngines(c *HeistV1alpha1Client, namespace string) *vaultKVSecretEngines {
	return &vaultKVSecretEngines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vaultKVSecretEngine, and returns the corresponding vaultKVSecretEngine object, and an error if there is any.
func (c *vaultKVSecretEngines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	result = &v1alpha1.VaultKVSecretEngine{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VaultKVSecretEngines that match those selectors.
func (c *vaultKVSecretEngines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultKVSecretEngineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VaultKVSecretEngineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vaultKVSecretEngines.
func (c *vaultKVSecretEngines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vaultKVSecretEngine and creates it.  Returns the server's representation of the vaultKVSecretEngine, and an error, if there is any.
func (c *vaultKVSecretEngines) Create(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.CreateOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	result = &v1alpha1.VaultKVSecretEngine{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultKVSecretEngine).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vaultKVSecretEngine and updates it. Returns the server's representation of the vaultKVSecretEngine, and an error, if there is any.
func (c *vaultKVSecretEngines) Update(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	result = &v1alpha1.VaultKVSecretEngine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		Name(vaultKVSecretEngine.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultKVSecretEngine).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vaultKVSecretEngines) UpdateStatus(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	result = &v1alpha1.VaultKVSecretEngine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		Name(vaultKVSecretEngine.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultKVSecretEngine).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vaultKVSecretEngine and deletes it. Returns an error if one occurs.
func (c *vaultKVSecretEngines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vaultKVSecretEngines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vaultKVSecretEngine.
func (c *vaultKVSecretEngines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultKVSecretEngine, err error) {
	result = &v1alpha1.VaultKVSecretEngine{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vaultkvsecretengines").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
