/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	scheme "github.com/youniqx/heist/pkg/client/heist.youniqx.com/v1alpha1/clientset/heist/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VaultTransitEnginesGetter has a method to return a VaultTransitEngineInterface.
// A group's client should implement this interface.
type VaultTransitEnginesGetter interface {
	VaultTransitEngines(namespace string) VaultTransitEngineInterface
}

// VaultTransitEngineInterface has methods to work with VaultTransitEngine resources.
type VaultTransitEngineInterface interface {
	Create(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.CreateOptions) (*v1alpha1.VaultTransitEngine, error)
	Update(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (*v1alpha1.VaultTransitEngine, error)
	UpdateStatus(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (*v1alpha1.VaultTransitEngine, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VaultTransitEngine, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VaultTransitEngineList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultTransitEngine, err error)
	VaultTransitEngineExpansion
}

// vaultTransitEngines implements VaultTransitEngineInterface
type vaultTransitEngines struct {
	client rest.Interface
	ns     string
}

// newVaultTransitEngines returns a VaultTransitEngines
func newVaultTransitEngines(c *HeistV1alpha1Client, namespace string) *vaultTransitEngines {
	return &vaultTransitEngines{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vaultTransitEngine, and returns the corresponding vaultTransitEngine object, and an error if there is any.
func (c *vaultTransitEngines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	result = &v1alpha1.VaultTransitEngine{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VaultTransitEngines that match those selectors.
func (c *vaultTransitEngines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultTransitEngineList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VaultTransitEngineList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vaultTransitEngines.
func (c *vaultTransitEngines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vaultTransitEngine and creates it.  Returns the server's representation of the vaultTransitEngine, and an error, if there is any.
func (c *vaultTransitEngines) Create(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.CreateOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	result = &v1alpha1.VaultTransitEngine{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultTransitEngine).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vaultTransitEngine and updates it. Returns the server's representation of the vaultTransitEngine, and an error, if there is any.
func (c *vaultTransitEngines) Update(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	result = &v1alpha1.VaultTransitEngine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		Name(vaultTransitEngine.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultTransitEngine).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vaultTransitEngines) UpdateStatus(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	result = &v1alpha1.VaultTransitEngine{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		Name(vaultTransitEngine.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultTransitEngine).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vaultTransitEngine and deletes it. Returns an error if one occurs.
func (c *vaultTransitEngines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vaultTransitEngines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaulttransitengines").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vaultTransitEngine.
func (c *vaultTransitEngines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultTransitEngine, err error) {
	result = &v1alpha1.VaultTransitEngine{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vaulttransitengines").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
