# permissions for end users to view vaultclientconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultclientconfig-viewer-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultclientconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultclientconfigs/status
  verbs:
  - get
