# permissions for end users to edit vaultkvsecretengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultkvsecretengine-editor-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecretengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecretengines/status
  verbs:
  - get
