# permissions for end users to view vaultkvsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultkvsecret-viewer-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecrets/status
  verbs:
  - get
