# permissions for end users to view vaultbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultbinding-viewer-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultbindings/status
  verbs:
  - get
