# permissions for end users to edit vaultcertificateroles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultcertificaterole-editor-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultcertificateroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultcertificateroles/status
  verbs:
  - get
