# permissions for end users to view vaultsyncsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultsyncsecret-viewer-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultsyncsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultsyncsecrets/status
  verbs:
  - get
