# permissions for end users to edit vaulttransitengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaulttransitengine-editor-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaulttransitengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaulttransitengines/status
  verbs:
  - get
