# permissions for end users to edit vaultsyncsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultsyncsecret-editor-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultsyncsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultsyncsecrets/status
  verbs:
  - get
