# permissions for end users to view vaultkvsecretengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vaultkvsecretengine-viewer-role
rules:
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecretengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - heist.youniqx.com
  resources:
  - vaultkvsecretengines/status
  verbs:
  - get
