//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/youniqx/heist/pkg/vault/pki"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionReason) DeepCopyInto(out *ConditionReason) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionReason.
func (in *ConditionReason) DeepCopy() *ConditionReason {
	if in == nil {
		return nil
	}
	out := new(ConditionReason)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionType) DeepCopyInto(out *ConditionType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionType.
func (in *ConditionType) DeepCopy() *ConditionType {
	if in == nil {
		return nil
	}
	out := new(ConditionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConditionsWrapper) DeepCopyInto(out *ConditionsWrapper) {
	*out = *in
	if in.Reasons != nil {
		in, out := &in.Reasons, &out.Reasons
		*out = new(ConditionReason)
		**out = **in
	}
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = new(ConditionType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConditionsWrapper.
func (in *ConditionsWrapper) DeepCopy() *ConditionsWrapper {
	if in == nil {
		return nil
	}
	out := new(ConditionsWrapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBinding) DeepCopyInto(out *VaultBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBinding.
func (in *VaultBinding) DeepCopy() *VaultBinding {
	if in == nil {
		return nil
	}
	out := new(VaultBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingAgentConfig) DeepCopyInto(out *VaultBindingAgentConfig) {
	*out = *in
	if in.CertificateTemplates != nil {
		in, out := &in.CertificateTemplates, &out.CertificateTemplates
		*out = make([]VaultCertificateTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Templates != nil {
		in, out := &in.Templates, &out.Templates
		*out = make([]VaultBindingValueTemplate, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingAgentConfig.
func (in *VaultBindingAgentConfig) DeepCopy() *VaultBindingAgentConfig {
	if in == nil {
		return nil
	}
	out := new(VaultBindingAgentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingCertificate) DeepCopyInto(out *VaultBindingCertificate) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingCertificateCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingCertificate.
func (in *VaultBindingCertificate) DeepCopy() *VaultBindingCertificate {
	if in == nil {
		return nil
	}
	out := new(VaultBindingCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingCertificateAuthority) DeepCopyInto(out *VaultBindingCertificateAuthority) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingCertificateAuthorityCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingCertificateAuthority.
func (in *VaultBindingCertificateAuthority) DeepCopy() *VaultBindingCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(VaultBindingCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingKV) DeepCopyInto(out *VaultBindingKV) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingKVCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingKV.
func (in *VaultBindingKV) DeepCopy() *VaultBindingKV {
	if in == nil {
		return nil
	}
	out := new(VaultBindingKV)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingList) DeepCopyInto(out *VaultBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingList.
func (in *VaultBindingList) DeepCopy() *VaultBindingList {
	if in == nil {
		return nil
	}
	out := new(VaultBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingSpec) DeepCopyInto(out *VaultBindingSpec) {
	*out = *in
	out.Subject = in.Subject
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingHeistCapability, len(*in))
		copy(*out, *in)
	}
	if in.KVSecrets != nil {
		in, out := &in.KVSecrets, &out.KVSecrets
		*out = make([]VaultBindingKV, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateAuthorities != nil {
		in, out := &in.CertificateAuthorities, &out.CertificateAuthorities
		*out = make([]VaultBindingCertificateAuthority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CertificateRoles != nil {
		in, out := &in.CertificateRoles, &out.CertificateRoles
		*out = make([]VaultBindingCertificate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TransitKeys != nil {
		in, out := &in.TransitKeys, &out.TransitKeys
		*out = make([]VaultBindingTransitKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Agent.DeepCopyInto(&out.Agent)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingSpec.
func (in *VaultBindingSpec) DeepCopy() *VaultBindingSpec {
	if in == nil {
		return nil
	}
	out := new(VaultBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingStatus) DeepCopyInto(out *VaultBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AppliedSpec.DeepCopyInto(&out.AppliedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingStatus.
func (in *VaultBindingStatus) DeepCopy() *VaultBindingStatus {
	if in == nil {
		return nil
	}
	out := new(VaultBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingSubject) DeepCopyInto(out *VaultBindingSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingSubject.
func (in *VaultBindingSubject) DeepCopy() *VaultBindingSubject {
	if in == nil {
		return nil
	}
	out := new(VaultBindingSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingTransitKey) DeepCopyInto(out *VaultBindingTransitKey) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingTransitKeyCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingTransitKey.
func (in *VaultBindingTransitKey) DeepCopy() *VaultBindingTransitKey {
	if in == nil {
		return nil
	}
	out := new(VaultBindingTransitKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultBindingValueTemplate) DeepCopyInto(out *VaultBindingValueTemplate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultBindingValueTemplate.
func (in *VaultBindingValueTemplate) DeepCopy() *VaultBindingValueTemplate {
	if in == nil {
		return nil
	}
	out := new(VaultBindingValueTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthority) DeepCopyInto(out *VaultCertificateAuthority) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthority.
func (in *VaultCertificateAuthority) DeepCopy() *VaultCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultCertificateAuthority) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityImport) DeepCopyInto(out *VaultCertificateAuthorityImport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityImport.
func (in *VaultCertificateAuthorityImport) DeepCopy() *VaultCertificateAuthorityImport {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityKVSecretRef) DeepCopyInto(out *VaultCertificateAuthorityKVSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityKVSecretRef.
func (in *VaultCertificateAuthorityKVSecretRef) DeepCopy() *VaultCertificateAuthorityKVSecretRef {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityKVSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityList) DeepCopyInto(out *VaultCertificateAuthorityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultCertificateAuthority, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityList.
func (in *VaultCertificateAuthorityList) DeepCopy() *VaultCertificateAuthorityList {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultCertificateAuthorityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityRef) DeepCopyInto(out *VaultCertificateAuthorityRef) {
	*out = *in
	out.KVSecrets = in.KVSecrets
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingCertificateAuthorityCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityRef.
func (in *VaultCertificateAuthorityRef) DeepCopy() *VaultCertificateAuthorityRef {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthoritySettings) DeepCopyInto(out *VaultCertificateAuthoritySettings) {
	*out = *in
	if in.SubjectAlternativeNames != nil {
		in, out := &in.SubjectAlternativeNames, &out.SubjectAlternativeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPSans != nil {
		in, out := &in.IPSans, &out.IPSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URISans != nil {
		in, out := &in.URISans, &out.URISans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OtherSans != nil {
		in, out := &in.OtherSans, &out.OtherSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TTL = in.TTL
	if in.PermittedDNSDomains != nil {
		in, out := &in.PermittedDNSDomains, &out.PermittedDNSDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthoritySettings.
func (in *VaultCertificateAuthoritySettings) DeepCopy() *VaultCertificateAuthoritySettings {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthoritySettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthoritySpec) DeepCopyInto(out *VaultCertificateAuthoritySpec) {
	*out = *in
	if in.Import != nil {
		in, out := &in.Import, &out.Import
		*out = new(VaultCertificateAuthorityImport)
		**out = **in
	}
	in.Subject.DeepCopyInto(&out.Subject)
	out.Tuning = in.Tuning
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthoritySpec.
func (in *VaultCertificateAuthoritySpec) DeepCopy() *VaultCertificateAuthoritySpec {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthoritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityStatus) DeepCopyInto(out *VaultCertificateAuthorityStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityStatus.
func (in *VaultCertificateAuthorityStatus) DeepCopy() *VaultCertificateAuthorityStatus {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthoritySubject) DeepCopyInto(out *VaultCertificateAuthoritySubject) {
	*out = *in
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Province != nil {
		in, out := &in.Province, &out.Province
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddress != nil {
		in, out := &in.StreetAddress, &out.StreetAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthoritySubject.
func (in *VaultCertificateAuthoritySubject) DeepCopy() *VaultCertificateAuthoritySubject {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthoritySubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateAuthorityTuning) DeepCopyInto(out *VaultCertificateAuthorityTuning) {
	*out = *in
	out.DefaultLeaseTTL = in.DefaultLeaseTTL
	out.MaxLeaseTTL = in.MaxLeaseTTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateAuthorityTuning.
func (in *VaultCertificateAuthorityTuning) DeepCopy() *VaultCertificateAuthorityTuning {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateAuthorityTuning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRef) DeepCopyInto(out *VaultCertificateRef) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingCertificateCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRef.
func (in *VaultCertificateRef) DeepCopy() *VaultCertificateRef {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRole) DeepCopyInto(out *VaultCertificateRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRole.
func (in *VaultCertificateRole) DeepCopy() *VaultCertificateRole {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultCertificateRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRoleList) DeepCopyInto(out *VaultCertificateRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultCertificateRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRoleList.
func (in *VaultCertificateRoleList) DeepCopy() *VaultCertificateRoleList {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultCertificateRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRoleSettings) DeepCopyInto(out *VaultCertificateRoleSettings) {
	*out = *in
	out.TTL = in.TTL
	out.MaxTTL = in.MaxTTL
	if in.AllowedDomains != nil {
		in, out := &in.AllowedDomains, &out.AllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedURISans != nil {
		in, out := &in.AllowedURISans, &out.AllowedURISans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedOtherSans != nil {
		in, out := &in.AllowedOtherSans, &out.AllowedOtherSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyUsage != nil {
		in, out := &in.KeyUsage, &out.KeyUsage
		*out = make([]pki.KeyUsage, len(*in))
		copy(*out, *in)
	}
	if in.ExtendedKeyUsage != nil {
		in, out := &in.ExtendedKeyUsage, &out.ExtendedKeyUsage
		*out = make([]pki.ExtendedKeyUsage, len(*in))
		copy(*out, *in)
	}
	if in.ExtendedKeyUsageOIDS != nil {
		in, out := &in.ExtendedKeyUsageOIDS, &out.ExtendedKeyUsageOIDS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PolicyIdentifiers != nil {
		in, out := &in.PolicyIdentifiers, &out.PolicyIdentifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.NotBeforeDuration = in.NotBeforeDuration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRoleSettings.
func (in *VaultCertificateRoleSettings) DeepCopy() *VaultCertificateRoleSettings {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRoleSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRoleSpec) DeepCopyInto(out *VaultCertificateRoleSpec) {
	*out = *in
	in.Subject.DeepCopyInto(&out.Subject)
	in.Settings.DeepCopyInto(&out.Settings)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRoleSpec.
func (in *VaultCertificateRoleSpec) DeepCopy() *VaultCertificateRoleSpec {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRoleStatus) DeepCopyInto(out *VaultCertificateRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRoleStatus.
func (in *VaultCertificateRoleStatus) DeepCopy() *VaultCertificateRoleStatus {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateRoleSubject) DeepCopyInto(out *VaultCertificateRoleSubject) {
	*out = *in
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OrganizationalUnit != nil {
		in, out := &in.OrganizationalUnit, &out.OrganizationalUnit
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locality != nil {
		in, out := &in.Locality, &out.Locality
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Province != nil {
		in, out := &in.Province, &out.Province
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StreetAddress != nil {
		in, out := &in.StreetAddress, &out.StreetAddress
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PostalCode != nil {
		in, out := &in.PostalCode, &out.PostalCode
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateRoleSubject.
func (in *VaultCertificateRoleSubject) DeepCopy() *VaultCertificateRoleSubject {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateRoleSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultCertificateTemplate) DeepCopyInto(out *VaultCertificateTemplate) {
	*out = *in
	if in.DNSSans != nil {
		in, out := &in.DNSSans, &out.DNSSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OtherSans != nil {
		in, out := &in.OtherSans, &out.OtherSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPSans != nil {
		in, out := &in.IPSans, &out.IPSans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URISans != nil {
		in, out := &in.URISans, &out.URISans
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.TTL = in.TTL
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultCertificateTemplate.
func (in *VaultCertificateTemplate) DeepCopy() *VaultCertificateTemplate {
	if in == nil {
		return nil
	}
	out := new(VaultCertificateTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultClientConfig) DeepCopyInto(out *VaultClientConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultClientConfig.
func (in *VaultClientConfig) DeepCopy() *VaultClientConfig {
	if in == nil {
		return nil
	}
	out := new(VaultClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultClientConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultClientConfigList) DeepCopyInto(out *VaultClientConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultClientConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultClientConfigList.
func (in *VaultClientConfigList) DeepCopy() *VaultClientConfigList {
	if in == nil {
		return nil
	}
	out := new(VaultClientConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultClientConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultClientConfigSpec) DeepCopyInto(out *VaultClientConfigSpec) {
	*out = *in
	if in.CACerts != nil {
		in, out := &in.CACerts, &out.CACerts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CertificateAuthorities != nil {
		in, out := &in.CertificateAuthorities, &out.CertificateAuthorities
		*out = make([]*VaultCertificateAuthorityRef, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VaultCertificateAuthorityRef)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.KvSecrets != nil {
		in, out := &in.KvSecrets, &out.KvSecrets
		*out = make([]*VaultKVSecretRef, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VaultKVSecretRef)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]*VaultCertificateRef, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VaultCertificateRef)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.TransitKeys != nil {
		in, out := &in.TransitKeys, &out.TransitKeys
		*out = make([]*VaultTransitKeyRef, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VaultTransitKeyRef)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Templates.DeepCopyInto(&out.Templates)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultClientConfigSpec.
func (in *VaultClientConfigSpec) DeepCopy() *VaultClientConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VaultClientConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultClientConfigStatus) DeepCopyInto(out *VaultClientConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultClientConfigStatus.
func (in *VaultClientConfigStatus) DeepCopy() *VaultClientConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VaultClientConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecret) DeepCopyInto(out *VaultKVSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecret.
func (in *VaultKVSecret) DeepCopy() *VaultKVSecret {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKVSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretEngine) DeepCopyInto(out *VaultKVSecretEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretEngine.
func (in *VaultKVSecretEngine) DeepCopy() *VaultKVSecretEngine {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKVSecretEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretEngineList) DeepCopyInto(out *VaultKVSecretEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultKVSecretEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretEngineList.
func (in *VaultKVSecretEngineList) DeepCopy() *VaultKVSecretEngineList {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKVSecretEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretEngineSpec) DeepCopyInto(out *VaultKVSecretEngineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretEngineSpec.
func (in *VaultKVSecretEngineSpec) DeepCopy() *VaultKVSecretEngineSpec {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretEngineStatus) DeepCopyInto(out *VaultKVSecretEngineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretEngineStatus.
func (in *VaultKVSecretEngineStatus) DeepCopy() *VaultKVSecretEngineStatus {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretEngineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretField) DeepCopyInto(out *VaultKVSecretField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretField.
func (in *VaultKVSecretField) DeepCopy() *VaultKVSecretField {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretList) DeepCopyInto(out *VaultKVSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultKVSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretList.
func (in *VaultKVSecretList) DeepCopy() *VaultKVSecretList {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKVSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretRef) DeepCopyInto(out *VaultKVSecretRef) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingKVCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretRef.
func (in *VaultKVSecretRef) DeepCopy() *VaultKVSecretRef {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretSpec) DeepCopyInto(out *VaultKVSecretSpec) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]*VaultKVSecretField, len(*in))
		for key, val := range *in {
			var outVal *VaultKVSecretField
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(VaultKVSecretField)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretSpec.
func (in *VaultKVSecretSpec) DeepCopy() *VaultKVSecretSpec {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKVSecretStatus) DeepCopyInto(out *VaultKVSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKVSecretStatus.
func (in *VaultKVSecretStatus) DeepCopy() *VaultKVSecretStatus {
	if in == nil {
		return nil
	}
	out := new(VaultKVSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncCertificate) DeepCopyInto(out *VaultSyncCertificate) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]VaultSyncCertificateField, len(*in))
		copy(*out, *in)
	}
	if in.AlternativeNames != nil {
		in, out := &in.AlternativeNames, &out.AlternativeNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncCertificate.
func (in *VaultSyncCertificate) DeepCopy() *VaultSyncCertificate {
	if in == nil {
		return nil
	}
	out := new(VaultSyncCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncCertificateAuthority) DeepCopyInto(out *VaultSyncCertificateAuthority) {
	*out = *in
	if in.Fields != nil {
		in, out := &in.Fields, &out.Fields
		*out = make([]VaultSyncCertificateField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncCertificateAuthority.
func (in *VaultSyncCertificateAuthority) DeepCopy() *VaultSyncCertificateAuthority {
	if in == nil {
		return nil
	}
	out := new(VaultSyncCertificateAuthority)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncCertificateAuthoritySource) DeepCopyInto(out *VaultSyncCertificateAuthoritySource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncCertificateAuthoritySource.
func (in *VaultSyncCertificateAuthoritySource) DeepCopy() *VaultSyncCertificateAuthoritySource {
	if in == nil {
		return nil
	}
	out := new(VaultSyncCertificateAuthoritySource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncCertificateField) DeepCopyInto(out *VaultSyncCertificateField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncCertificateField.
func (in *VaultSyncCertificateField) DeepCopy() *VaultSyncCertificateField {
	if in == nil {
		return nil
	}
	out := new(VaultSyncCertificateField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncCertificateSource) DeepCopyInto(out *VaultSyncCertificateSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncCertificateSource.
func (in *VaultSyncCertificateSource) DeepCopy() *VaultSyncCertificateSource {
	if in == nil {
		return nil
	}
	out := new(VaultSyncCertificateSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncKVSecretSource) DeepCopyInto(out *VaultSyncKVSecretSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncKVSecretSource.
func (in *VaultSyncKVSecretSource) DeepCopy() *VaultSyncKVSecretSource {
	if in == nil {
		return nil
	}
	out := new(VaultSyncKVSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncKvSecret) DeepCopyInto(out *VaultSyncKvSecret) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncKvSecret.
func (in *VaultSyncKvSecret) DeepCopy() *VaultSyncKvSecret {
	if in == nil {
		return nil
	}
	out := new(VaultSyncKvSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecret) DeepCopyInto(out *VaultSyncSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecret.
func (in *VaultSyncSecret) DeepCopy() *VaultSyncSecret {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultSyncSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecretList) DeepCopyInto(out *VaultSyncSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultSyncSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecretList.
func (in *VaultSyncSecretList) DeepCopy() *VaultSyncSecretList {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultSyncSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecretSource) DeepCopyInto(out *VaultSyncSecretSource) {
	*out = *in
	if in.CertificateAuthority != nil {
		in, out := &in.CertificateAuthority, &out.CertificateAuthority
		*out = new(VaultSyncCertificateAuthoritySource)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(VaultSyncCertificateSource)
		**out = **in
	}
	if in.KVSecret != nil {
		in, out := &in.KVSecret, &out.KVSecret
		*out = new(VaultSyncKVSecretSource)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecretSource.
func (in *VaultSyncSecretSource) DeepCopy() *VaultSyncSecretSource {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecretSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecretSpec) DeepCopyInto(out *VaultSyncSecretSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.CertificateTemplates != nil {
		in, out := &in.CertificateTemplates, &out.CertificateTemplates
		*out = make([]VaultCertificateTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]VaultSyncSecretSource, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecretSpec.
func (in *VaultSyncSecretSpec) DeepCopy() *VaultSyncSecretSpec {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecretStatus) DeepCopyInto(out *VaultSyncSecretStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AppliedSpec.DeepCopyInto(&out.AppliedSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecretStatus.
func (in *VaultSyncSecretStatus) DeepCopy() *VaultSyncSecretStatus {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecretStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSyncSecretTarget) DeepCopyInto(out *VaultSyncSecretTarget) {
	*out = *in
	if in.AdditionalLabels != nil {
		in, out := &in.AdditionalLabels, &out.AdditionalLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdditionalAnnotations != nil {
		in, out := &in.AdditionalAnnotations, &out.AdditionalAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSyncSecretTarget.
func (in *VaultSyncSecretTarget) DeepCopy() *VaultSyncSecretTarget {
	if in == nil {
		return nil
	}
	out := new(VaultSyncSecretTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitEngine) DeepCopyInto(out *VaultTransitEngine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitEngine.
func (in *VaultTransitEngine) DeepCopy() *VaultTransitEngine {
	if in == nil {
		return nil
	}
	out := new(VaultTransitEngine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitEngine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitEngineList) DeepCopyInto(out *VaultTransitEngineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultTransitEngine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitEngineList.
func (in *VaultTransitEngineList) DeepCopy() *VaultTransitEngineList {
	if in == nil {
		return nil
	}
	out := new(VaultTransitEngineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitEngineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitEngineSpec) DeepCopyInto(out *VaultTransitEngineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitEngineSpec.
func (in *VaultTransitEngineSpec) DeepCopy() *VaultTransitEngineSpec {
	if in == nil {
		return nil
	}
	out := new(VaultTransitEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitEngineStatus) DeepCopyInto(out *VaultTransitEngineStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitEngineStatus.
func (in *VaultTransitEngineStatus) DeepCopy() *VaultTransitEngineStatus {
	if in == nil {
		return nil
	}
	out := new(VaultTransitEngineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitKey) DeepCopyInto(out *VaultTransitKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitKey.
func (in *VaultTransitKey) DeepCopy() *VaultTransitKey {
	if in == nil {
		return nil
	}
	out := new(VaultTransitKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitKeyList) DeepCopyInto(out *VaultTransitKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultTransitKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitKeyList.
func (in *VaultTransitKeyList) DeepCopy() *VaultTransitKeyList {
	if in == nil {
		return nil
	}
	out := new(VaultTransitKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultTransitKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitKeyRef) DeepCopyInto(out *VaultTransitKeyRef) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]VaultBindingTransitKeyCapability, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitKeyRef.
func (in *VaultTransitKeyRef) DeepCopy() *VaultTransitKeyRef {
	if in == nil {
		return nil
	}
	out := new(VaultTransitKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitKeySpec) DeepCopyInto(out *VaultTransitKeySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitKeySpec.
func (in *VaultTransitKeySpec) DeepCopy() *VaultTransitKeySpec {
	if in == nil {
		return nil
	}
	out := new(VaultTransitKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTransitKeyStatus) DeepCopyInto(out *VaultTransitKeyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.AppliedSpec = in.AppliedSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTransitKeyStatus.
func (in *VaultTransitKeyStatus) DeepCopy() *VaultTransitKeyStatus {
	if in == nil {
		return nil
	}
	out := new(VaultTransitKeyStatus)
	in.DeepCopyInto(out)
	return out
}
