apiVersion: heist.youniqx.com/v1alpha1
kind: VaultBinding
metadata:
  name: some-binding
spec:
  subject:
    name: example-sa
  certificateAuthorities:
    - name: tls-intermediate
      capabilities:
      - read_private
      - read_public
  certificates:
    - name: tls-cert
      capabilities:
      - issue
      - sign_csr
  kvSecrets:
    - name: example-secret
      capabilities:
      - read
  transitKeys:
    - name: example-key
      capabilities:
      - sign
      - read
  agent:
    certificates:
      - certificate: tls-cert
        alias: tls
        commonName: "example.com"
        dnsSans:
          - "example.com"
          - "*.example.com"
    templates:
      - path: "intermediate.key"
        template: '{{ caField "tls-intermediate" "private_key" }}'
      - path: "intermediate.crt"
        template: '{{ caField "tls-intermediate" "certificate" }}'
      - path: "intermediate.chain"
        template: '{{ caField "tls-intermediate" "cert_chain" }}'
      - path: "tls.key"
        template: '{{ certField "tls" "private_key" }}'
      - path: "tls.crt"
        template: '{{ certField "tls" "certificate" }}'
      - path: "password"
        template: '{{ kvSecret "example-secret" "autogenerated-field" }}'
      - path: "apiKey"
        template: '{{ kvSecret "example-secret" "static-field" }}'
