apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSyncSecret
metadata:
  name: other-namespace-sync
spec:
  target:
    name: synced-secret
    namespace: default
  data:
    full_chain:
      certificateAuthority:
        name: tls-intermediate
        field: full_cert_chain
    chain:
      certificateAuthority:
        name: tls-intermediate
        field: cert_chain
    cert:
      certificateAuthority:
        name: tls-intermediate
        field: certificate
    key:
      certificateAuthority:
        name: tls-intermediate
        field: private_key
---
apiVersion: heist.youniqx.com/v1alpha1
kind: VaultSyncSecret
metadata:
  name: legacy-sync
certificates:
  - common_name: example.com
    fields:
      - field: certificate
        key: tls.crt
      - field: private_key
        key: tls.key
    name: tls-cert
secret:
  name: tls-creds
