/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// VaultBindingListerExpansion allows custom methods to be added to
// VaultBindingLister.
type VaultBindingListerExpansion interface{}

// VaultBindingNamespaceListerExpansion allows custom methods to be added to
// VaultBindingNamespaceLister.
type VaultBindingNamespaceListerExpansion interface{}

// VaultCertificateAuthorityListerExpansion allows custom methods to be added to
// VaultCertificateAuthorityLister.
type VaultCertificateAuthorityListerExpansion interface{}

// VaultCertificateAuthorityNamespaceListerExpansion allows custom methods to be added to
// VaultCertificateAuthorityNamespaceLister.
type VaultCertificateAuthorityNamespaceListerExpansion interface{}

// VaultCertificateRoleListerExpansion allows custom methods to be added to
// VaultCertificateRoleLister.
type VaultCertificateRoleListerExpansion interface{}

// VaultCertificateRoleNamespaceListerExpansion allows custom methods to be added to
// VaultCertificateRoleNamespaceLister.
type VaultCertificateRoleNamespaceListerExpansion interface{}

// VaultClientConfigListerExpansion allows custom methods to be added to
// VaultClientConfigLister.
type VaultClientConfigListerExpansion interface{}

// VaultClientConfigNamespaceListerExpansion allows custom methods to be added to
// VaultClientConfigNamespaceLister.
type VaultClientConfigNamespaceListerExpansion interface{}

// VaultKVSecretListerExpansion allows custom methods to be added to
// VaultKVSecretLister.
type VaultKVSecretListerExpansion interface{}

// VaultKVSecretNamespaceListerExpansion allows custom methods to be added to
// VaultKVSecretNamespaceLister.
type VaultKVSecretNamespaceListerExpansion interface{}

// VaultKVSecretEngineListerExpansion allows custom methods to be added to
// VaultKVSecretEngineLister.
type VaultKVSecretEngineListerExpansion interface{}

// VaultKVSecretEngineNamespaceListerExpansion allows custom methods to be added to
// VaultKVSecretEngineNamespaceLister.
type VaultKVSecretEngineNamespaceListerExpansion interface{}

// VaultSyncSecretListerExpansion allows custom methods to be added to
// VaultSyncSecretLister.
type VaultSyncSecretListerExpansion interface{}

// VaultSyncSecretNamespaceListerExpansion allows custom methods to be added to
// VaultSyncSecretNamespaceLister.
type VaultSyncSecretNamespaceListerExpansion interface{}

// VaultTransitEngineListerExpansion allows custom methods to be added to
// VaultTransitEngineLister.
type VaultTransitEngineListerExpansion interface{}

// VaultTransitEngineNamespaceListerExpansion allows custom methods to be added to
// VaultTransitEngineNamespaceLister.
type VaultTransitEngineNamespaceListerExpansion interface{}

// VaultTransitKeyListerExpansion allows custom methods to be added to
// VaultTransitKeyLister.
type VaultTransitKeyListerExpansion interface{}

// VaultTransitKeyNamespaceListerExpansion allows custom methods to be added to
// VaultTransitKeyNamespaceLister.
type VaultTransitKeyNamespaceListerExpansion interface{}
