/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultTransitEngines implements VaultTransitEngineInterface
type FakeVaultTransitEngines struct {
	Fake *FakeHeistV1alpha1
	ns   string
}

var vaulttransitenginesResource = schema.GroupVersionResource{Group: "heist.youniqx.com", Version: "v1alpha1", Resource: "vaulttransitengines"}

var vaulttransitenginesKind = schema.GroupVersionKind{Group: "heist.youniqx.com", Version: "v1alpha1", Kind: "VaultTransitEngine"}

// Get takes name of the vaultTransitEngine, and returns the corresponding vaultTransitEngine object, and an error if there is any.
func (c *FakeVaultTransitEngines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaulttransitenginesResource, c.ns, name), &v1alpha1.VaultTransitEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultTransitEngine), err
}

// List takes label and field selectors, and returns the list of VaultTransitEngines that match those selectors.
func (c *FakeVaultTransitEngines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultTransitEngineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaulttransitenginesResource, vaulttransitenginesKind, c.ns, opts), &v1alpha1.VaultTransitEngineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultTransitEngineList{ListMeta: obj.(*v1alpha1.VaultTransitEngineList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultTransitEngineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultTransitEngines.
func (c *FakeVaultTransitEngines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaulttransitenginesResource, c.ns, opts))

}

// Create takes the representation of a vaultTransitEngine and creates it.  Returns the server's representation of the vaultTransitEngine, and an error, if there is any.
func (c *FakeVaultTransitEngines) Create(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.CreateOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaulttransitenginesResource, c.ns, vaultTransitEngine), &v1alpha1.VaultTransitEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultTransitEngine), err
}

// Update takes the representation of a vaultTransitEngine and updates it. Returns the server's representation of the vaultTransitEngine, and an error, if there is any.
func (c *FakeVaultTransitEngines) Update(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultTransitEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaulttransitenginesResource, c.ns, vaultTransitEngine), &v1alpha1.VaultTransitEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultTransitEngine), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultTransitEngines) UpdateStatus(ctx context.Context, vaultTransitEngine *v1alpha1.VaultTransitEngine, opts v1.UpdateOptions) (*v1alpha1.VaultTransitEngine, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaulttransitenginesResource, "status", c.ns, vaultTransitEngine), &v1alpha1.VaultTransitEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultTransitEngine), err
}

// Delete takes name of the vaultTransitEngine and deletes it. Returns an error if one occurs.
func (c *FakeVaultTransitEngines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaulttransitenginesResource, c.ns, name, opts), &v1alpha1.VaultTransitEngine{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultTransitEngines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaulttransitenginesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultTransitEngineList{})
	return err
}

// Patch applies the patch and returns the patched vaultTransitEngine.
func (c *FakeVaultTransitEngines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultTransitEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaulttransitenginesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultTransitEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultTransitEngine), err
}
