/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultBindings implements VaultBindingInterface
type FakeVaultBindings struct {
	Fake *FakeHeistV1alpha1
	ns   string
}

var vaultbindingsResource = schema.GroupVersionResource{Group: "heist.youniqx.com", Version: "v1alpha1", Resource: "vaultbindings"}

var vaultbindingsKind = schema.GroupVersionKind{Group: "heist.youniqx.com", Version: "v1alpha1", Kind: "VaultBinding"}

// Get takes name of the vaultBinding, and returns the corresponding vaultBinding object, and an error if there is any.
func (c *FakeVaultBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultbindingsResource, c.ns, name), &v1alpha1.VaultBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultBinding), err
}

// List takes label and field selectors, and returns the list of VaultBindings that match those selectors.
func (c *FakeVaultBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultbindingsResource, vaultbindingsKind, c.ns, opts), &v1alpha1.VaultBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultBindingList{ListMeta: obj.(*v1alpha1.VaultBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultBindings.
func (c *FakeVaultBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultbindingsResource, c.ns, opts))

}

// Create takes the representation of a vaultBinding and creates it.  Returns the server's representation of the vaultBinding, and an error, if there is any.
func (c *FakeVaultBindings) Create(ctx context.Context, vaultBinding *v1alpha1.VaultBinding, opts v1.CreateOptions) (result *v1alpha1.VaultBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultbindingsResource, c.ns, vaultBinding), &v1alpha1.VaultBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultBinding), err
}

// Update takes the representation of a vaultBinding and updates it. Returns the server's representation of the vaultBinding, and an error, if there is any.
func (c *FakeVaultBindings) Update(ctx context.Context, vaultBinding *v1alpha1.VaultBinding, opts v1.UpdateOptions) (result *v1alpha1.VaultBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultbindingsResource, c.ns, vaultBinding), &v1alpha1.VaultBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultBinding), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultBindings) UpdateStatus(ctx context.Context, vaultBinding *v1alpha1.VaultBinding, opts v1.UpdateOptions) (*v1alpha1.VaultBinding, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaultbindingsResource, "status", c.ns, vaultBinding), &v1alpha1.VaultBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultBinding), err
}

// Delete takes name of the vaultBinding and deletes it. Returns an error if one occurs.
func (c *FakeVaultBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaultbindingsResource, c.ns, name, opts), &v1alpha1.VaultBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultbindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultBindingList{})
	return err
}

// Patch applies the patch and returns the patched vaultBinding.
func (c *FakeVaultBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultBinding), err
}
