/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultClientConfigs implements VaultClientConfigInterface
type FakeVaultClientConfigs struct {
	Fake *FakeHeistV1alpha1
	ns   string
}

var vaultclientconfigsResource = schema.GroupVersionResource{Group: "heist.youniqx.com", Version: "v1alpha1", Resource: "vaultclientconfigs"}

var vaultclientconfigsKind = schema.GroupVersionKind{Group: "heist.youniqx.com", Version: "v1alpha1", Kind: "VaultClientConfig"}

// Get takes name of the vaultClientConfig, and returns the corresponding vaultClientConfig object, and an error if there is any.
func (c *FakeVaultClientConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultClientConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultclientconfigsResource, c.ns, name), &v1alpha1.VaultClientConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultClientConfig), err
}

// List takes label and field selectors, and returns the list of VaultClientConfigs that match those selectors.
func (c *FakeVaultClientConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultClientConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultclientconfigsResource, vaultclientconfigsKind, c.ns, opts), &v1alpha1.VaultClientConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultClientConfigList{ListMeta: obj.(*v1alpha1.VaultClientConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultClientConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultClientConfigs.
func (c *FakeVaultClientConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultclientconfigsResource, c.ns, opts))

}

// Create takes the representation of a vaultClientConfig and creates it.  Returns the server's representation of the vaultClientConfig, and an error, if there is any.
func (c *FakeVaultClientConfigs) Create(ctx context.Context, vaultClientConfig *v1alpha1.VaultClientConfig, opts v1.CreateOptions) (result *v1alpha1.VaultClientConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultclientconfigsResource, c.ns, vaultClientConfig), &v1alpha1.VaultClientConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultClientConfig), err
}

// Update takes the representation of a vaultClientConfig and updates it. Returns the server's representation of the vaultClientConfig, and an error, if there is any.
func (c *FakeVaultClientConfigs) Update(ctx context.Context, vaultClientConfig *v1alpha1.VaultClientConfig, opts v1.UpdateOptions) (result *v1alpha1.VaultClientConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultclientconfigsResource, c.ns, vaultClientConfig), &v1alpha1.VaultClientConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultClientConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultClientConfigs) UpdateStatus(ctx context.Context, vaultClientConfig *v1alpha1.VaultClientConfig, opts v1.UpdateOptions) (*v1alpha1.VaultClientConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaultclientconfigsResource, "status", c.ns, vaultClientConfig), &v1alpha1.VaultClientConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultClientConfig), err
}

// Delete takes name of the vaultClientConfig and deletes it. Returns an error if one occurs.
func (c *FakeVaultClientConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaultclientconfigsResource, c.ns, name, opts), &v1alpha1.VaultClientConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultClientConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultclientconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultClientConfigList{})
	return err
}

// Patch applies the patch and returns the patched vaultClientConfig.
func (c *FakeVaultClientConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultClientConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultclientconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultClientConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultClientConfig), err
}
