/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultKVSecretEngines implements VaultKVSecretEngineInterface
type FakeVaultKVSecretEngines struct {
	Fake *FakeHeistV1alpha1
	ns   string
}

var vaultkvsecretenginesResource = schema.GroupVersionResource{Group: "heist.youniqx.com", Version: "v1alpha1", Resource: "vaultkvsecretengines"}

var vaultkvsecretenginesKind = schema.GroupVersionKind{Group: "heist.youniqx.com", Version: "v1alpha1", Kind: "VaultKVSecretEngine"}

// Get takes name of the vaultKVSecretEngine, and returns the corresponding vaultKVSecretEngine object, and an error if there is any.
func (c *FakeVaultKVSecretEngines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultkvsecretenginesResource, c.ns, name), &v1alpha1.VaultKVSecretEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultKVSecretEngine), err
}

// List takes label and field selectors, and returns the list of VaultKVSecretEngines that match those selectors.
func (c *FakeVaultKVSecretEngines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultKVSecretEngineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultkvsecretenginesResource, vaultkvsecretenginesKind, c.ns, opts), &v1alpha1.VaultKVSecretEngineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultKVSecretEngineList{ListMeta: obj.(*v1alpha1.VaultKVSecretEngineList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultKVSecretEngineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultKVSecretEngines.
func (c *FakeVaultKVSecretEngines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultkvsecretenginesResource, c.ns, opts))

}

// Create takes the representation of a vaultKVSecretEngine and creates it.  Returns the server's representation of the vaultKVSecretEngine, and an error, if there is any.
func (c *FakeVaultKVSecretEngines) Create(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.CreateOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultkvsecretenginesResource, c.ns, vaultKVSecretEngine), &v1alpha1.VaultKVSecretEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultKVSecretEngine), err
}

// Update takes the representation of a vaultKVSecretEngine and updates it. Returns the server's representation of the vaultKVSecretEngine, and an error, if there is any.
func (c *FakeVaultKVSecretEngines) Update(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (result *v1alpha1.VaultKVSecretEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultkvsecretenginesResource, c.ns, vaultKVSecretEngine), &v1alpha1.VaultKVSecretEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultKVSecretEngine), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultKVSecretEngines) UpdateStatus(ctx context.Context, vaultKVSecretEngine *v1alpha1.VaultKVSecretEngine, opts v1.UpdateOptions) (*v1alpha1.VaultKVSecretEngine, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaultkvsecretenginesResource, "status", c.ns, vaultKVSecretEngine), &v1alpha1.VaultKVSecretEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultKVSecretEngine), err
}

// Delete takes name of the vaultKVSecretEngine and deletes it. Returns an error if one occurs.
func (c *FakeVaultKVSecretEngines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaultkvsecretenginesResource, c.ns, name, opts), &v1alpha1.VaultKVSecretEngine{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultKVSecretEngines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultkvsecretenginesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultKVSecretEngineList{})
	return err
}

// Patch applies the patch and returns the patched vaultKVSecretEngine.
func (c *FakeVaultKVSecretEngines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultKVSecretEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultkvsecretenginesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultKVSecretEngine{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultKVSecretEngine), err
}
