/*
Copyright 2022 youniqx Identity AG.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/youniqx/heist/pkg/apis/heist.youniqx.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVaultCertificateRoles implements VaultCertificateRoleInterface
type FakeVaultCertificateRoles struct {
	Fake *FakeHeistV1alpha1
	ns   string
}

var vaultcertificaterolesResource = v1alpha1.SchemeGroupVersion.WithResource("vaultcertificateroles")

var vaultcertificaterolesKind = v1alpha1.SchemeGroupVersion.WithKind("VaultCertificateRole")

// Get takes name of the vaultCertificateRole, and returns the corresponding vaultCertificateRole object, and an error if there is any.
func (c *FakeVaultCertificateRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VaultCertificateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(vaultcertificaterolesResource, c.ns, name), &v1alpha1.VaultCertificateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultCertificateRole), err
}

// List takes label and field selectors, and returns the list of VaultCertificateRoles that match those selectors.
func (c *FakeVaultCertificateRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VaultCertificateRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(vaultcertificaterolesResource, vaultcertificaterolesKind, c.ns, opts), &v1alpha1.VaultCertificateRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VaultCertificateRoleList{ListMeta: obj.(*v1alpha1.VaultCertificateRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.VaultCertificateRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested vaultCertificateRoles.
func (c *FakeVaultCertificateRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(vaultcertificaterolesResource, c.ns, opts))

}

// Create takes the representation of a vaultCertificateRole and creates it.  Returns the server's representation of the vaultCertificateRole, and an error, if there is any.
func (c *FakeVaultCertificateRoles) Create(ctx context.Context, vaultCertificateRole *v1alpha1.VaultCertificateRole, opts v1.CreateOptions) (result *v1alpha1.VaultCertificateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(vaultcertificaterolesResource, c.ns, vaultCertificateRole), &v1alpha1.VaultCertificateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultCertificateRole), err
}

// Update takes the representation of a vaultCertificateRole and updates it. Returns the server's representation of the vaultCertificateRole, and an error, if there is any.
func (c *FakeVaultCertificateRoles) Update(ctx context.Context, vaultCertificateRole *v1alpha1.VaultCertificateRole, opts v1.UpdateOptions) (result *v1alpha1.VaultCertificateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(vaultcertificaterolesResource, c.ns, vaultCertificateRole), &v1alpha1.VaultCertificateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultCertificateRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVaultCertificateRoles) UpdateStatus(ctx context.Context, vaultCertificateRole *v1alpha1.VaultCertificateRole, opts v1.UpdateOptions) (*v1alpha1.VaultCertificateRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(vaultcertificaterolesResource, "status", c.ns, vaultCertificateRole), &v1alpha1.VaultCertificateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultCertificateRole), err
}

// Delete takes name of the vaultCertificateRole and deletes it. Returns an error if one occurs.
func (c *FakeVaultCertificateRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(vaultcertificaterolesResource, c.ns, name, opts), &v1alpha1.VaultCertificateRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVaultCertificateRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(vaultcertificaterolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VaultCertificateRoleList{})
	return err
}

// Patch applies the patch and returns the patched vaultCertificateRole.
func (c *FakeVaultCertificateRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VaultCertificateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(vaultcertificaterolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VaultCertificateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VaultCertificateRole), err
}
